### ISSUE TITLE
No Installataion Package

### ISSUE THREAD

**Issue by pije76** [g-battaglia/AstrochartSVG#1]
When pip3 install astro_svg then says "ERROR: No matching distribution found for astro_svg"

Can you provide the library please?

**Comment by g-battaglia** [comment]
Hi, I'm sorry this package is here just for legacy reasons, all it's future it's now part of kerykeion, the library on which is based. I've removed from pip though. You can find kerykeion here: https://github.com/g-battaglia/kerykeion

**Comment by pije76** [comment]
Thank you for your information @g-battaglia
Btw what difference between kerykeion, BirthchartSVG & kerykeion_charts?
